<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        // Seeds for groups
        DB::table('groups')->insert([
            ['group_id' => 1, 'group_name' => 'INFORMASI 1', 'group_rate' => '0.05', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 2, 'group_name' => 'INFORMASI 2', 'group_rate' => '0.05', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 3, 'group_name' => 'INFORMASI 3', 'group_rate' => '0.2', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 4, 'group_name' => 'INFORMASI 4', 'group_rate' => '0.15', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 5, 'group_name' => 'INFORMASI 5', 'group_rate' => '0.3', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 6, 'group_name' => 'INFORMASI 6', 'group_rate' => '0.25', 'created_at' => now(), 'updated_at' => now()],
        ]);

        // Seeds for group_items
        DB::table('group_items')->insert([
            ['group_item_id' => 1, 'group_id' => 1, 'group_item_name' => 'Umur Pemohon', 'group_item_rate' => 0.3, 'created_at' => now(), 'updated_at' => now()],
            ['group_item_id' => 2, 'group_id' => 1, 'group_item_name' => 'Umur Pemohon + Tenor', 'group_item_rate' => 0.1, 'created_at' => now(), 'updated_at' => now()],
            ['group_item_id' => 3, 'group_id' => 1, 'group_item_name' => 'Status Perkawinan', 'group_item_rate' => 0.4, 'created_at' => now(), 'updated_at' => now()],
            ['group_item_id' => 4, 'group_id' => 1, 'group_item_name' => 'Pendidikan', 'group_item_rate' => 0.2, 'created_at' => now(), 'updated_at' => now()],
            ['group_item_id' => 5, 'group_id' => 2, 'group_item_name' => 'Alamat tempat tinggal', 'group_item_rate' => 0.4, 'created_at' => now(), 'updated_at' => now()],
            ['group_item_id' => 6, 'group_id' => 2, 'group_item_name' => 'Kepemilikan tempat tinggal', 'group_item_rate' => 0.3, 'created_at' => now(), 'updated_at' => now()],
            ['group_item_id' => 7, 'group_id' => 2, 'group_item_name' => 'Lama menempati', 'group_item_rate' => 0.3, 'created_at' => now(), 'updated_at' => now()],
            ['group_item_id' => 8, 'group_id' => 3, 'group_item_name' => 'Kategori Perusahaan', 'group_item_rate' => 0.2, 'created_at' => now(), 'updated_at' => now()],
            ['group_item_id' => 9, 'group_id' => 3, 'group_item_name' => 'Jabatan', 'group_item_rate' => 0.2, 'created_at' => now(), 'updated_at' => now()],
            ['group_item_id' => 10, 'group_id' => 3, 'group_item_name' => 'Lama bekerja', 'group_item_rate' => 0.2, 'created_at' => now(), 'updated_at' => now()],
            ['group_item_id' => 11, 'group_id' => 3, 'group_item_name' => 'Pendapatan THP', 'group_item_rate' => 0.4, 'created_at' => now(), 'updated_at' => now()],
            ['group_item_id' => 12, 'group_id' => 4, 'group_item_name' => 'Rekening Bank', 'group_item_rate' => 0.1, 'created_at' => now(), 'updated_at' => now()],
            ['group_item_id' => 13, 'group_id' => 4, 'group_item_name' => 'Rata-rata saldo per bulannya', 'group_item_rate' => 0.15, 'created_at' => now(), 'updated_at' => now()],
            ['group_item_id' => 14, 'group_id' => 4, 'group_item_name' => 'Track record pembayaran angsuran', 'group_item_rate' => 0.15, 'created_at' => now(), 'updated_at' => now()],
            ['group_item_id' => 15, 'group_id' => 4, 'group_item_name' => 'Track Data SLIK', 'group_item_rate' => 0.4, 'created_at' => now(), 'updated_at' => now()],
            ['group_item_id' => 16, 'group_id' => 4, 'group_item_name' => 'Kepemilikan Kartu Kredit', 'group_item_rate' => 0.2, 'created_at' => now(), 'updated_at' => now()],
            ['group_item_id' => 17, 'group_id' => 5, 'group_item_name' => 'Tenor', 'group_item_rate' => 0.25, 'created_at' => now(), 'updated_at' => now()],
            ['group_item_id' => 18, 'group_id' => 5, 'group_item_name' => 'Debt Service Ratio', 'group_item_rate' => 0.75, 'created_at' => now(), 'updated_at' => now()],
            ['group_item_id' => 19, 'group_id' => 6, 'group_item_name' => 'Hasil Appraisal', 'group_item_rate' => 0.1, 'created_at' => now(), 'updated_at' => now()],
            ['group_item_id' => 20, 'group_id' => 6, 'group_item_name' => 'Luas Bangunan', 'group_item_rate' => 0.2, 'created_at' => now(), 'updated_at' => now()],
            ['group_item_id' => 21, 'group_id' => 6, 'group_item_name' => 'Tujuan dari Pembiayaan', 'group_item_rate' => 0.1, 'created_at' => now(), 'updated_at' => now()],
            ['group_item_id' => 22, 'group_id' => 6, 'group_item_name' => 'LTV', 'group_item_rate' => 0.6, 'created_at' => now(), 'updated_at' => now()],
        ]);

        // Seeds for items
        DB::table('items')->insert([
            ['item_id' => 1, 'group_item_id' => 1, 'item_name' => '1. 56 - 65 Tahun', 'item_rate' => 25.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 2, 'group_item_id' => 1, 'item_name' => '2. 21 - 30 Tahun', 'item_rate' => 50.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 3, 'group_item_id' => 1, 'item_name' => '3. 31 - 45 Tahun', 'item_rate' => 100.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 4, 'group_item_id' => 1, 'item_name' => '4. 46 - 55 Tahun', 'item_rate' => 75.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 5, 'group_item_id' => 2, 'item_name' => '1. Diatas Ketentuan', 'item_rate' => 25.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 6, 'group_item_id' => 2, 'item_name' => '2. Dibawah Ketentuan', 'item_rate' => 100.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 7, 'group_item_id' => 3, 'item_name' => '1. Belum Kawin dengan > 2 tanggungan', 'item_rate' => 25.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 8, 'group_item_id' => 3, 'item_name' => '2. Belum Kawin dengan <= 2 tanggungan', 'item_rate' => 45.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 9, 'group_item_id' => 3, 'item_name' => '3. Belum Kawin dengan 0 tanggungan', 'item_rate' => 65.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 10, 'group_item_id' => 3, 'item_name' => '4. Kawin dengan > 2 tanggungan', 'item_rate' => 85.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 11, 'group_item_id' => 3, 'item_name' => '5. Kawin dengan <= 2 tanggungan', 'item_rate' => 100.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 12, 'group_item_id' => 4, 'item_name' => '1. SMA atau dibawahnya', 'item_rate' => 25.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 13, 'group_item_id' => 4, 'item_name' => '2. D1, D2, D3, D4', 'item_rate' => 50.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 14, 'group_item_id' => 4, 'item_name' => '3. S1', 'item_rate' => 75.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 15, 'group_item_id' => 4, 'item_name' => '4. Master atau diatasnya (S2, S3)', 'item_rate' => 100.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 16, 'group_item_id' => 5, 'item_name' => '1. Tidak sesuai dengan data Bank', 'item_rate' => 25.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 17, 'group_item_id' => 5, 'item_name' => '2. Sesuai dengan data Bank', 'item_rate' => 100.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 18, 'group_item_id' => 6, 'item_name' => '1. Lain-lain', 'item_rate' => 25.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 19, 'group_item_id' => 6, 'item_name' => '2. Sewa / Kontrak', 'item_rate' => 50.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 20, 'group_item_id' => 6, 'item_name' => '3. Milik sendiri masih diangsur', 'item_rate' => 75.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 21, 'group_item_id' => 6, 'item_name' => '4. Milik sendiri', 'item_rate' => 100.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 22, 'group_item_id' => 7, 'item_name' => '1. <= 2 tahun', 'item_rate' => 25.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 23, 'group_item_id' => 7, 'item_name' => '2. > 2 - 5 tahun', 'item_rate' => 50.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 24, 'group_item_id' => 7, 'item_name' => '3. > 5 - 8 tahun', 'item_rate' => 75.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 25, 'group_item_id' => 7, 'item_name' => '4. > 8 tahun', 'item_rate' => 100.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 26, 'group_item_id' => 8, 'item_name' => '1. Lembaga Departemen', 'item_rate' => 100.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 27, 'group_item_id' => 8, 'item_name' => '2. BUMD', 'item_rate' => 25.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 28, 'group_item_id' => 8, 'item_name' => '3. SWASTA tidak punya rating', 'item_rate' => 100.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 29, 'group_item_id' => 8, 'item_name' => '4. SWASTA dengan rating', 'item_rate' => 25.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 30, 'group_item_id' => 8, 'item_name' => '5. SWASTA Katergori I', 'item_rate' => 75.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 31, 'group_item_id' => 8, 'item_name' => '6. SWASTA Kategori II', 'item_rate' => 50.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 32, 'group_item_id' => 8, 'item_name' => '7. SWASTA Kategori III', 'item_rate' => 0.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 33, 'group_item_id' => 9, 'item_name' => '1. Staff', 'item_rate' => 25.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 34, 'group_item_id' => 9, 'item_name' => '2. Direktur', 'item_rate' => 75.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 35, 'group_item_id' => 9, 'item_name' => '3. Komisaris', 'item_rate' => 100.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 36, 'group_item_id' => 10, 'item_name' => '1. <= 2 Tahun', 'item_rate' => 0.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 37, 'group_item_id' => 10, 'item_name' => '2. > 2 - 5 Tahun', 'item_rate' => 25.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 38, 'group_item_id' => 10, 'item_name' => '3. > 5 - 10 Tahun', 'item_rate' => 75.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 39, 'group_item_id' => 10, 'item_name' => '4. > 10 Tahun', 'item_rate' => 100.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 40, 'group_item_id' => 11, 'item_name' => '1. <= Rp 10 juta', 'item_rate' => 25.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 41, 'group_item_id' => 11, 'item_name' => '2. > Rp 10 - Rp 25 juta', 'item_rate' => 50.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 42, 'group_item_id' => 11, 'item_name' => '3. > Rp 25 - Rp 50 juta', 'item_rate' => 75.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 43, 'group_item_id' => 11, 'item_name' => '4. > Rp 50 juta', 'item_rate' => 100.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 44, 'group_item_id' => 12, 'item_name' => '1. Tidak ada', 'item_rate' => 25.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 45, 'group_item_id' => 12, 'item_name' => '2. Tabungan', 'item_rate' => 50.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 46, 'group_item_id' => 12, 'item_name' => '3. Giro', 'item_rate' => 75.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 47, 'group_item_id' => 12, 'item_name' => '4. Tabungan/Giro + Deposito', 'item_rate' => 100.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 48, 'group_item_id' => 13, 'item_name' => '1. <= Rp 10 juta', 'item_rate' => 25.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 49, 'group_item_id' => 13, 'item_name' => '2. Rp 10 - Rp 25 juta', 'item_rate' => 50.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 50, 'group_item_id' => 13, 'item_name' => '3. Rp 25 - Rp 50 juta', 'item_rate' => 75.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 51, 'group_item_id' => 13, 'item_name' => '4. > Rp 50 juta', 'item_rate' => 100.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 52, 'group_item_id' => 14, 'item_name' => '1. Peminjam baru', 'item_rate' => 25.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 53, 'group_item_id' => 14, 'item_name' => '2. Angsuran terlambat tapi lancar', 'item_rate' => 50.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 54, 'group_item_id' => 14, 'item_name' => '3. Angsuran tepat waktu', 'item_rate' => 100.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 55, 'group_item_id' => 15, 'item_name' => '1. Kolektibilitas 3 sd 5', 'item_rate' => 0.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 56, 'group_item_id' => 15, 'item_name' => '2. Ada tunggakan < 3 bulan', 'item_rate' => 50.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 57, 'group_item_id' => 15, 'item_name' => '3. Tidak ada fasilitas', 'item_rate' => 75.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 58, 'group_item_id' => 15, 'item_name' => '4. Lancar', 'item_rate' => 100.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 59, 'group_item_id' => 16, 'item_name' => '1. Tidak Ada', 'item_rate' => 25.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 60, 'group_item_id' => 16, 'item_name' => '2. Basic', 'item_rate' => 50.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 61, 'group_item_id' => 16, 'item_name' => '3. Gold', 'item_rate' => 75.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 62, 'group_item_id' => 16, 'item_name' => '4. Platinum atau diatasnya', 'item_rate' => 100.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 63, 'group_item_id' => 17, 'item_name' => '1. > 15 Tahun', 'item_rate' => 25.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 64, 'group_item_id' => 17, 'item_name' => '2. > 10 - 15 Tahun', 'item_rate' => 50.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 65, 'group_item_id' => 17, 'item_name' => '3. > 5 - 10 Tahun', 'item_rate' => 75.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 66, 'group_item_id' => 17, 'item_name' => '4. <= 5 Tahun', 'item_rate' => 100.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 67, 'group_item_id' => 18, 'item_name' => '1. > 50%', 'item_rate' => 0.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 68, 'group_item_id' => 18, 'item_name' => '2. > 40 - 50%', 'item_rate' => 50.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 69, 'group_item_id' => 18, 'item_name' => '3. > 30 - 40%', 'item_rate' => 75.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 70, 'group_item_id' => 18, 'item_name' => '4. <= 30%', 'item_rate' => 100.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 71, 'group_item_id' => 19, 'item_name' => '1. Tidak Direkomendasikan', 'item_rate' => 0.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 72, 'group_item_id' => 19, 'item_name' => '2. Marketable', 'item_rate' => 100.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 73, 'group_item_id' => 20, 'item_name' => '1. > 200 M2', 'item_rate' => 25.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 74, 'group_item_id' => 20, 'item_name' => '2. > 100 - 200 M2', 'item_rate' => 50.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 75, 'group_item_id' => 20, 'item_name' => '3. > 45 - 100 M2', 'item_rate' => 75.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 76, 'group_item_id' => 20, 'item_name' => '4. <= 45 M2', 'item_rate' => 100.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 77, 'group_item_id' => 21, 'item_name' => '1. Lain-Lain', 'item_rate' => 25.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 78, 'group_item_id' => 21, 'item_name' => '2. Disewakan/Investasi', 'item_rate' => 50.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 79, 'group_item_id' => 21, 'item_name' => '3. Renovasi', 'item_rate' => 75.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 80, 'group_item_id' => 21, 'item_name' => '4. Pertama & Ditempati Sendiri', 'item_rate' => 100.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 81, 'group_item_id' => 22, 'item_name' => '1. LTV > 90%', 'item_rate' => 25.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 82, 'group_item_id' => 22, 'item_name' => '2. LTV > 80%', 'item_rate' => 50.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 83, 'group_item_id' => 22, 'item_name' => '3. LTV > 70%', 'item_rate' => 75.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 84, 'group_item_id' => 22, 'item_name' => '4. LTV <= 70%', 'item_rate' => 100.0, 'created_at' => now(), 'updated_at' => now()],
            ['item_id' => 85, 'group_item_id' => 22, 'item_name' => '5. LTV > 100%', 'item_rate' => 0.0, 'created_at' => now(), 'updated_at' => now()],
        ]);
    }
}